export const metadata = {
    title: 'Add Product | Next JS Project',
    description: 'Generated by create next app',
  }

const addProduct = () => {
    return (
        <div>
            <h1>Add Product</h1>
        </div>
    );
};

export default addProduct;